{
 "title": "track_recommender",
 "time": { "from": "2024-10-29T08:09:19.000Z", "to": "2024-10-29T08:24:21.000Z" },
 "panels": [
  {
   "title": "Recommendation system progress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "TP_total/ (TP_total+ FP_total)", "legendFormat": "Precision@5 (Total)" },
    {
     "expr": "TP_total / (TP_total + FN_total)",
     "legendFormat": "Recall@5 (Total)"
    }
   ]
  },
  {
   "title": "Recommendations accuracy change",
   "type": "timeseries",
   "description": "Table shows Precison, Recall and F1 score for the recommendations\n\n",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(TP_total[5m]) / (rate(TP_total[5m]) + rate(FP_total[5m]))",
     "legendFormat": "Precison@5 [5m rate]"
    },
    {
     "expr": "rate(TP_total[5m]) / (rate(TP_total[5m]) + rate(FN_total[5m]))",
     "legendFormat": "Recall@5 [5m rate]"
    },
    {
     "expr": "2 * (\n    (rate(TP_total[5m]) / (rate(TP_total[5m]) + rate(FP_total[5m]))) * \n    (rate(TP_total[5m]) / (rate(TP_total[5m]) + rate(FN_total[5m])))\n) / (\n    (rate(TP_total[5m]) / (rate(TP_total[5m]) + rate(FP_total[5m]))) + \n    (rate(TP_total[5m]) / (rate(TP_total[5m]) + rate(FN_total[5m])))\n)\n\n",
     "legendFormat": "F1@5 [5m rate]"
    }
   ]
  },
  {
   "title": "RAM ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"events:5050\", job=\"scrapping-events-service\"}",
     "legendFormat": "Events Service"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"recommendation:1300\", job=\"scrapping-main-app\"}",
     "legendFormat": "Recommendation Service"
    }
   ]
  },
  {
   "title": "Recommendations service https request duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler=\"/recommendations_offline/\", job=\"scrapping-main-app\", instance=\"recommendation:1300\", method=\"POST\"}[5m])) by (le))\n",
     "legendFormat": "95% Recommendatiions https put quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{handler=\"/recommendations_offline/\", job=\"scrapping-main-app\", instance=\"recommendation:1300\", method=\"POST\"}[5m])) by (le))\n",
     "legendFormat": "50% Recommendatiions https put quantile"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(http_request_duration_seconds_bucket{handler=\"/recommendations_offline/\", job=\"scrapping-main-app\", instance=\"recommendation:1300\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "10% Recommendatiions https put quantile"
    }
   ]
  },
  {
   "title": "CPU consumption rate per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"events:5050\", job=\"scrapping-events-service\"}[5m]) * 60",
     "legendFormat": "Events service"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"recommendation:1300\", job=\"scrapping-main-app\"}[5m]) * 60",
     "legendFormat": "Recommendations service"
    }
   ]
  },
  {
   "title": "Total CPU Time Seconds ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 15 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"events:5050\", job=\"scrapping-events-service\"}",
     "legendFormat": "Events service"
    },
    {
     "expr": "process_cpu_seconds_total{instance=\"recommendation:1300\", job=\"scrapping-main-app\"}",
     "legendFormat": "Recommendation service"
    }
   ]
  },
  {
   "title": "Events Service https request duration(95/50/10 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler=\"/put\", job=\"scrapping-events-service\", method=\"POST\"}[5m])) by (le))\n",
     "legendFormat": "95% Events https request post"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{handler=\"/put\", job=\"scrapping-events-service\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "Median Events https request post"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(http_request_duration_seconds_bucket{handler=\"/put\", job=\"scrapping-events-service\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "10% Events https request post"
    }
   ]
  }
 ]
}