global:
  # как часто собирать метрики?
  scrape_interval: 10s
  
  # если за это время сборщик не собрал метрики, то процесс прерывается
  scrape_timeout: 7s
  

scrape_configs:
  # Main application metrics
  - job_name: 'scrapping-main-app'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - recommendation:1300

  # Events service metrics
  - job_name: 'scrapping-events-service'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - events:5050