version: '3.8'

networks:
  my_custom_network:
    driver: bridge

services:
  my_base_image:
    image: anufriev2510/app_base:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile.base
    networks:
      - my_custom_network

  recommendation:
    build:
      context: ../
      dockerfile: docker/Dockerfile.recommendation
    depends_on:
      - my_base_image 
    ports:
      - "1300:1300" 
    env_file:
      - ../.env  
    networks:
      - my_custom_network

  events:
    build:
      context: ../
      dockerfile: docker/Dockerfile.events
    depends_on:
      - my_base_image  
    ports:
      - "5050:5050" 
    env_file:
      - ../.env  
    networks:
      - my_custom_network

  features:
    build:
      context: ../
      dockerfile: docker/Dockerfile.features
    depends_on:
      - my_base_image
    ports:
      - "8010:8010"   
    env_file:
      - ../.env  
    networks:
      - my_custom_network

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "${PROM_PORT_VM}:${PROM_PORT_DOCKER}"  # Add your environment variables for ports
    volumes:
      - "../app/monitor/prometheus.yml:/etc/prometheus/prometheus.yml"
    env_file:
      - .env
    networks:
      - my_custom_network

  grafana:
    image: grafana/grafana
    env_file:
      - .env
    ports:
      - "${GRAFANA_PORT_VM}:${GRAFANA_PORT_DOCKER}"  # Add your environment variables for ports
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
    networks:
      - my_custom_network

